name: "Go: Run Tests - Other OS"
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test-mac:
    name: Test MacOS
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Run tests
        uses: ./go/actions/test

  test-win:
    if: github.repository_owner == 'github'
    name: Test Windows
    runs-on: windows-latest-xl
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Run tests
        uses: ./go/actions/test
